// Pre-existing code. Grabs the HTML element with an ID of "generate", in practice a button with the intended function of generating a new password
var generateBtn = document.querySelector("#generate");

// Pre-existing code. Takes the password generated by the function generatePassword, which is the code to be written, and passes that value to be displayed in the HTML.
function writePassword() {
  var password = generatePassword();
  var passwordText = document.querySelector("#password");

  passwordText.value = password;

}

// Add event listener to generate button, triggers the writePassword function events
generateBtn.addEventListener("click", writePassword);

//TODO: Generate the generatePassword function that returns the final password

function generatePassword() {
  //TODO: prompt, ask the length of a password, save it to a variable
  var passwordLength = prompt("How many characters long should the password be?")
  if (typeof passwordLength !== "number") {
    alert("That's not a number! Plase try again.");
    passwordLength = prompt("How many characters long should the password be?");
  } else if (passwordLength > 128) {
    alert("A password can be at most 128 characters.");
    passwordLength = prompt("How many characters long should the password be?");
  } else if (passwordLength < 8) {
    alert("A password cannot be less than 8 characters.");
    passwordLength = prompt("How many characters long should the password be?");
  }

  // Ask the user whether the password should have these characters
  var hasLowercase = confirm("Should this password have lowercase letters?");
  var hasUppercase = confirm("Should this password have uppercase letters?");
  var hasNumbers = confirm("Should this password have numeric characters?");
  var hasSpecial = confirm("Should this password have special letters?");
  if (!hasLowercase && !hasUppercase && !hasNumbers && !hasSpecial) {
    alert("We can't generate a password without any characters! Please try again.");
    break;
  }

  //Arrays of the characters that can be used in generating a password
  var lowerLetters = "abcdefghiklmnopqrstuvwxyz";
  var upperLetters = "ABCDEFGHIJKLMNOPQRSTUVWXTZ";
  var nums = "0123456789";
  var special = "";
  var allChars = [lowerLetters, upperLetters, nums, special];


  var password = "";

  //For the requested length of the password,
  for (i = 0; i < passwordLength; i++) {
    var whichLetters = Math.floor(Math.random() * 4);
    var cont = false;
    var arr;

    while (cont === false) {
      if (hasLowercase && whichLetters === 0) {
        arr = allChars[0];
        cont = true;
      } else if (hasUppercase && whichLetters === 1) {
        arr = allChars[0];
        cont = true;
      } else if (hasNumbers && whichLetters === 2) {
        arr = allChars[0];
        cont = true;
      } else if (hasLowercase && whichLetters === 0) {
        arr = allChars[0];
        cont = true;
      } else {
        whichLetters = Math.floor(Math.random() * 4);
      }
    }

  }
}